// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-shared-scenario.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { z } from "npm:zod@^3.25.76";
var get_shared_scenario_default = defineTool({
  name: "get_shared_scenario",
  title: "Get shared scenario",
  description: "Fetch a publicly shared SmartFunnel scenario by its share ID. Returns the full scenario JSON, active lead type, AI conclusion, and creation date.",
  inputSchema: {
    share_id: z.string().min(1).describe("The share ID (uuid) of the shared scenario, as found in the /share/:shareId URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ share_id }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("shared_scenarios").select("id, active_lead_type, ai_conclusion, created_at, scenario").eq("id", share_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Shared scenario not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-recent-shared-scenarios.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_recent_shared_scenarios_default = defineTool2({
  name: "list_recent_shared_scenarios",
  title: "List recent shared scenarios",
  description: "List the most recently created public shared SmartFunnel scenarios (id, active lead type, created_at). Useful for browsing available shared funnels.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of scenarios to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient2(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("shared_scenarios").select("id, active_lead_type, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "smartfunnel-mcp",
  title: "SmartFunnel AI MCP",
  version: "0.1.0",
  instructions: "Tools for SmartFunnel AI (Ads School). Use `list_recent_shared_scenarios` to browse publicly shared funnels and `get_shared_scenario` to fetch the full JSON of a specific shared scenario by its share ID.",
  tools: [list_recent_shared_scenarios_default, get_shared_scenario_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
